### ISSUE TITLE
Version 1.0 tracking issue

### ISSUE THREAD

**Issue by mfreeborn** [plotly/plotly.rs#104]
This is a stub issue to track what is necessary to release a 1.0 version.

I'll be adding to this over time to show what has been implemented and what still needs doing before we can call it a 1.0 release.

### [Basic Charts](https://plotly.com/javascript/basic-charts/)

- [x] Scatter
- [x] Line
- [x] Bar
- [x] Pie
- [x] Bubble
- [x] Dot
- [ ] Filled area
- [ ] Sunburst
- [x] Sankey
- [ ] Point Cloud
- [ ] Treemaps
- [x] Tables

### [Statistical Charts](https://plotly.com/javascript/statistical-charts/)

- [x] Box
- [x] Histograms
- [ ] 2D density
- [ ] Violin
- [ ] Parallel Categories
- [ ] Splom

### [Scientific Charts](https://plotly.com/javascript/scientific-charts/)

- [x] Contour
- [x] Heatmaps
- [ ] Ternary
- [ ] Parallel Coordinates
- [ ] Log
- [x] Scatter polar
- [ ] Bar polar
- [ ] Carpet
- [ ] Contour carpet

### [Financial Charts](https://plotly.com/javascript/financial-charts/)

- [ ] Waterfall
- [ ] Indicator
- [x] Candlestick
- [ ] Funnel
- [ ] Funnel area
- [x] OHLC

### Maps

- [x] Density heatmap
- [ ] Choropleth
- [ ] Scatter geo
- [x] Scatter mapbox

### [3D Charts](https://plotly.com/javascript/3d-charts/)

- [x] Scatter
- [x] Surface
- [x] Mesh
- [ ] Cone
- [ ] Streamtube
- [ ] Isosurface

## API

- [ ] Make the library panic-safe by replacing `unwrap()` and `expect` with `Result` (#33)

## Features

- [x] Wasm support (complete as of v0.8.0)
- [ ] Sliders

## Meta
- [x] Add code coverage

**Comment by mfreeborn** [comment]
Obsolete
